<?= $this->extend('layouts/admin_master') ?>

<?= $this->section('content') ?>
<?php $stats = $tournamentStats ?? []; $canManage = can('tournaments.manage'); $categoriesById = []; foreach (($categories ?? []) as $category) $categoriesById[(int) $category->id] = $category; ?>
<div class="erp-action-bar">
    <div class="d-flex gap-2 flex-wrap"><a href="/admin/tournaments/show/<?= (int) $tournament->id ?>" class="erp-btn"><i class="bi bi-arrow-left"></i> Chi tiết giải</a><a href="/admin/tournaments/bracket?tournament_id=<?= (int) $tournament->id ?>" class="erp-btn"><i class="bi bi-diagram-3"></i> Cây đấu</a><a href="/admin/tournaments/scheduler?category_id=<?= (int) ($categories[0]->id ?? 0) ?>" class="erp-btn"><i class="bi bi-calendar3"></i> Xếp lịch</a><a href="/admin/print-center?tournament_id=<?= (int) $tournament->id ?>" class="erp-btn"><i class="bi bi-printer"></i> In</a><a href="/admin/tournaments/registrations/<?= (int) $tournament->id ?>/export?<?= http_build_query($registrationFilters ?? []) ?>" class="erp-btn"><i class="bi bi-filetype-csv"></i> Xuất CSV</a></div>
    <div class="d-flex gap-2 flex-wrap"><span class="erp-summary-chip">Tổng <strong><?= (int) ($stats['registrations'] ?? count($registrations ?? [])) ?></strong></span><span class="erp-summary-chip">Đã duyệt <strong><?= (int) ($stats['approved'] ?? 0) ?></strong></span><span class="erp-summary-chip">Chờ duyệt <strong><?= (int) ($stats['pending'] ?? 0) ?></strong></span></div>
</div>

<?php if ($canManage): ?><section class="erp-card mb-3">
    <div class="erp-card-header"><div><strong>Thêm vận động viên vào giải</strong><div class="erp-muted">Tương đương thao tác gán VĐV nhanh từ màn điều hành KKM.</div></div></div>
    <div class="erp-card-body"><form method="post" action="/admin/tournaments/registrations/<?= (int) $tournament->id ?>/store" class="row g-2 align-items-end"><?= csrf_field() ?><div class="col-lg-3"><label class="form-label">Vận động viên</label><select name="player_id" class="form-select" required><option value="">Chọn VĐV</option><?php foreach (($players ?? []) as $player): ?><option value="<?= (int) $player->id ?>"><?= esc($player->full_name) ?> · <?= esc($player->player_code ?? '') ?></option><?php endforeach; ?></select></div><div class="col-lg-3"><label class="form-label">Hạng mục</label><select name="category_id" class="form-select" required><option value="">Chọn hạng mục</option><?php foreach (($categories ?? []) as $category): ?><option value="<?= (int) $category->id ?>"><?= esc($category->name_vi) ?></option><?php endforeach; ?></select></div><div class="col-lg-2"><label class="form-label">Thanh toán</label><select name="payment_status" class="form-select"><option value="unpaid">Chưa thu</option><option value="paid">Đã thu</option><option value="partial">Một phần</option></select></div><div class="col-lg-2"><label class="form-label">Liên hệ</label><input name="contact_phone" class="form-control" placeholder="Số điện thoại"></div><div class="col-lg-2"><div class="form-check mb-2"><input class="form-check-input" type="checkbox" name="quick_approve" value="1" id="quickApprove"><label class="form-check-label" for="quickApprove">Duyệt nhanh</label></div><button class="btn btn-primary w-100"><i class="bi bi-person-plus me-1"></i>Thêm VĐV</button></div></form></div>
</section><?php endif; ?>

<form method="get" class="erp-filter-bar"><div class="d-flex flex-wrap gap-2 align-items-center"><input name="search" class="erp-control" placeholder="Tên, SĐT, mã invoice" value="<?= esc($registrationFilters['search'] ?? '') ?>"><select name="category_id" class="erp-select"><option value="">Tất cả hạng mục</option><?php foreach (($categories ?? []) as $category): ?><option value="<?= (int) $category->id ?>" <?= (int) ($registrationFilters['category_id'] ?? 0) === (int) $category->id ? 'selected' : '' ?>><?= esc($category->name_vi) ?></option><?php endforeach; ?></select><select name="approval_status" class="erp-select"><option value="">Duyệt: tất cả</option><option value="pending" <?= ($registrationFilters['approval_status'] ?? '') === 'pending' ? 'selected' : '' ?>>Chờ duyệt</option><option value="approved" <?= ($registrationFilters['approval_status'] ?? '') === 'approved' ? 'selected' : '' ?>>Đã duyệt</option><option value="rejected" <?= ($registrationFilters['approval_status'] ?? '') === 'rejected' ? 'selected' : '' ?>>Từ chối</option></select><select name="payment_status" class="erp-select"><option value="">Thanh toán: tất cả</option><option value="unpaid" <?= ($registrationFilters['payment_status'] ?? '') === 'unpaid' ? 'selected' : '' ?>>Chưa thu</option><option value="paid" <?= ($registrationFilters['payment_status'] ?? '') === 'paid' ? 'selected' : '' ?>>Đã thu</option></select><select name="checkin_status" class="erp-select"><option value="">Check-in: tất cả</option><option value="checked_in" <?= ($registrationFilters['checkin_status'] ?? '') === 'checked_in' ? 'selected' : '' ?>>Đã check-in</option><option value="pending" <?= ($registrationFilters['checkin_status'] ?? '') === 'pending' ? 'selected' : '' ?>>Chưa check-in</option></select><select name="per_page" class="erp-select"><option value="20">20 dòng</option><option value="50">50 dòng</option><option value="100">100 dòng</option></select></div><div class="d-flex gap-2"><button class="erp-btn erp-btn-primary" type="submit"><i class="bi bi-funnel"></i> Lọc</button><a class="erp-btn erp-btn-ghost" href="/admin/tournaments/registrations/<?= (int) $tournament->id ?>">Xóa</a></div></form>
<section class="erp-card"><div class="erp-card-header"><strong>Danh sách đăng ký</strong><span class="erp-muted">Hiển thị <?= count($registrations ?? []) ?> / <?= (int) ($registrationPage['total'] ?? count($registrations ?? [])) ?> · Review, thanh toán và check-in</span></div><div class="table-responsive"><table class="erp-table"><thead><tr><th>VĐV / đội</th><th>Hạng mục</th><th>Invoice</th><th>Thanh toán</th><th>Duyệt</th><th>Check-in</th><th>Thao tác</th></tr></thead><tbody>
<?php foreach (($registrations ?? []) as $registration): $checkin = $registration->checkin_status ?? (! empty($registration->checked_in_at) ? 'checked_in' : 'pending'); ?>
    <tr><td><strong><?= esc($registration->contact_name ?? 'Chưa có tên') ?></strong><div class="erp-muted"><?= esc($registration->contact_phone ?? '-') ?></div></td><td><?= esc($registration->category_name ?? ($categoriesById[(int) ($registration->category_id ?? 0)]->name_vi ?? '-')) ?></td><td><?= esc($registration->invoice_code ?? '-') ?><div class="erp-muted"><?= format_money($registration->invoice_amount ?? 0) ?></div></td><td><?= renderStatusBadge($registration->payment_status ?? 'unpaid', 'payment') ?></td><td><?= renderStatusBadge($registration->approval_status ?? 'pending') ?></td><td><?= renderStatusBadge($checkin, 'booking') ?></td><td class="col-actions"><?php if ($canManage): ?><div class="d-flex gap-1 flex-wrap"><?php if (($registration->approval_status ?? '') === 'pending'): ?><form method="post" action="/admin/tournaments/registrations/<?= (int) $registration->id ?>/approve"><?= csrf_field() ?><button class="btn btn-sm btn-success" title="Duyệt"><i class="bi bi-check-lg"></i></button></form><form method="post" action="/admin/tournaments/registrations/<?= (int) $registration->id ?>/reject"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger" title="Từ chối"><i class="bi bi-x-lg"></i></button></form><?php endif; ?><form method="post" action="/admin/tournaments/registrations/<?= (int) $registration->id ?>/checkin"><?= csrf_field() ?><input type="hidden" name="status" value="<?= $checkin === 'checked_in' ? 'pending' : 'checked_in' ?>"><button class="btn btn-sm btn-outline-primary" title="<?= $checkin === 'checked_in' ? 'Hủy check-in' : 'Check-in' ?>"><i class="bi <?= $checkin === 'checked_in' ? 'bi-arrow-counterclockwise' : 'bi-qr-code-scan' ?>"></i></button></form><form method="post" action="/admin/tournaments/registrations/<?= (int) $registration->id ?>/delete" onsubmit="return confirm('Xóa hồ sơ này khỏi giải?')"><?= csrf_field() ?><button class="btn btn-sm btn-outline-secondary" title="Xóa"><i class="bi bi-trash"></i></button></form></div><?php endif; ?></td></tr>
<?php endforeach; ?>
<?php if (empty($registrations)): ?><tr><td colspan="7" class="text-center erp-muted py-4">Chưa có đăng ký.</td></tr><?php endif; ?>
</tbody></table></div></section>
<?php if (($registrationPage['pages'] ?? 1) > 1): ?><div class="erp-pagination"><span class="erp-muted">Trang <?= (int) $registrationPage['page'] ?>/<?= (int) $registrationPage['pages'] ?></span><div class="btn-group btn-group-sm"><?php for ($p = max(1, (int) $registrationPage['page'] - 2); $p <= min((int) $registrationPage['pages'], (int) $registrationPage['page'] + 2); $p++): ?><a class="btn btn-outline-secondary <?= $p === (int) $registrationPage['page'] ? 'active' : '' ?>" href="/admin/tournaments/registrations/<?= (int) $tournament->id ?>?<?= http_build_query(array_merge($registrationFilters ?? [], ['page' => $p, 'per_page' => $registrationPage['perPage'] ?? 20])) ?>"><?= $p ?></a><?php endfor; ?></div></div><?php endif; ?>
<?= $this->endSection() ?>
