<?= $this->extend('layouts/admin_master') ?>
<?= $this->section('content') ?>

<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">Quầy walk-in</h1><p class="text-muted mb-0">Tạo booking tại quầy, check-in và checkout theo phiên có audit.</p></div><span class="badge text-bg-primary">Hôm nay</span></div>
<div class="row g-4">
    <div class="col-xl-5"><div class="card shadow-sm"><div class="card-header">Tạo phiên khách tại quầy</div><div class="card-body"><form method="post" action="<?= base_url('admin/walk-ins/store') ?>"><?= csrf_field() ?><div class="row g-2 mb-3"><div class="col-6"><label class="form-label">Chi nhánh</label><select name="branch_id" class="form-select" required><option value="">-- chọn --</option><?php foreach ($branches as $branch): ?><option value="<?= (int) $branch->id ?>"><?= esc($branch->name) ?></option><?php endforeach; ?></select></div><div class="col-6"><label class="form-label">Sân</label><select name="court_id" class="form-select" required><option value="">-- chọn --</option><?php foreach ($courts as $court): ?><option value="<?= (int) $court->id ?>"><?= esc($court->code . ' - ' . ($court->name_vi ?? '')) ?></option><?php endforeach; ?></select></div></div><div class="mb-3"><label class="form-label">Người chơi đã có hồ sơ</label><select name="player_id" class="form-select"><option value="">Khách vãng lai</option><?php foreach ($players as $player): ?><option value="<?= (int) $player->id ?>"><?= esc($player->full_name . ' - ' . ($player->phone ?? '')) ?></option><?php endforeach; ?></select></div><div class="row g-2 mb-3"><div class="col-4"><label class="form-label">Ngày</label><input type="date" name="booking_date" value="<?= date('Y-m-d') ?>" required class="form-control"></div><div class="col-4"><label class="form-label">Từ</label><input type="time" name="start_time" value="<?= date('H:i') ?>" required class="form-control"></div><div class="col-4"><label class="form-label">Đến</label><input type="time" name="end_time" required class="form-control"></div></div><div class="row g-2 mb-3"><div class="col-6"><label class="form-label">Tên khách</label><input name="customer_name" class="form-control"></div><div class="col-6"><label class="form-label">Điện thoại</label><input name="customer_phone" class="form-control"></div></div><div class="row g-2 mb-3"><div class="col-8"><label class="form-label">Ghi chú</label><input name="note" class="form-control"></div><div class="col-4"><label class="form-label">Session key</label><input name="session_key" class="form-control" maxlength="100"></div></div><button class="btn btn-primary w-100">Tạo walk-in</button></form></div></div></div>
    <div class="col-xl-7"><div class="card shadow-sm"><div class="card-header">Phiên hôm nay</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Khách</th><th>Booking</th><th>Trạng thái</th><th>Thời gian</th><th></th></tr></thead><tbody><?php if (!$entries): ?><tr><td colspan="5" class="text-center text-muted py-4">Chưa có phiên walk-in.</td></tr><?php endif; ?><?php foreach ($entries as $entry): ?><tr><td><?= esc($entry->customer_name) ?><br><small class="text-muted"><?= esc($entry->customer_phone) ?></small></td><td>#<?= (int) $entry->booking_id ?></td><td><span class="badge text-bg-<?= $entry->status === 'checked_in' ? 'success' : ($entry->status === 'open' ? 'warning' : 'secondary') ?>"><?= esc($entry->status) ?></span></td><td><?= esc($entry->created_at) ?></td><td class="text-nowrap"><?php if ($entry->status === 'open'): ?><form method="post" action="<?= base_url('admin/walk-ins/check-in/' . $entry->id) ?>" class="d-inline"><?= csrf_field() ?><button class="btn btn-sm btn-outline-success">Check-in</button></form><?php elseif ($entry->status === 'checked_in'): ?><form method="post" action="<?= base_url('admin/walk-ins/checkout/' . $entry->id) ?>" class="d-inline"><?= csrf_field() ?><button class="btn btn-sm btn-outline-primary">Checkout</button></form><?php endif; ?><?php if (in_array($entry->status, ['open', 'checked_in'], true)): ?><form method="post" action="<?= base_url('admin/walk-ins/cancel/' . $entry->id) ?>" class="d-inline"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger">Hủy</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div>

<?= $this->endSection() ?>
