<?= $this->extend('layouts/admin_master') ?>
<?= $this->section('content') ?>

<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">Báo cáo vận hành</h1><p class="text-muted mb-0">Doanh thu và booking theo ngày, chỉ trong tenant hiện tại.</p></div><a class="btn btn-outline-success" href="<?= base_url('admin/operations-report/csv?' . http_build_query(['from' => $report['from'], 'to' => $report['to'], 'branch_id' => $branchId])) ?>"><i class="bi bi-download"></i> Xuất CSV</a></div>
<div class="card shadow-sm mb-4"><div class="card-body"><form class="row g-2 align-items-end"><div class="col-md-3"><label class="form-label">Từ ngày</label><input type="date" name="from" value="<?= esc($report['from']) ?>" class="form-control"></div><div class="col-md-3"><label class="form-label">Đến ngày</label><input type="date" name="to" value="<?= esc($report['to']) ?>" class="form-control"></div><div class="col-md-3"><label class="form-label">Chi nhánh</label><select name="branch_id" class="form-select"><option value="">Tất cả</option><?php foreach ($branches as $branch): ?><option value="<?= (int) $branch->id ?>" <?= $branchId === (int) $branch->id ? 'selected' : '' ?>><?= esc($branch->name) ?></option><?php endforeach; ?></select></div><div class="col-md-3"><button class="btn btn-primary w-100">Lọc báo cáo</button></div></form></div></div>
<div class="row g-3 mb-4"><?php foreach ([['Booking', (int) ($report['summary']['bookings'] ?? 0)], ['Doanh thu booking', number_format((float) ($report['summary']['revenue'] ?? 0), 0, ',', '.') . 'đ'], ['Đã thu booking', number_format((float) ($report['summary']['collected'] ?? 0), 0, ',', '.') . 'đ'], ['Hóa đơn', (int) ($report['commerce']['invoices'] ?? 0)], ['Đã thu hóa đơn', number_format((float) ($report['commerce']['collected'] ?? 0), 0, ',', '.') . 'đ'], ['Công nợ', number_format((float) ($report['commerce']['outstanding'] ?? 0), 0, ',', '.') . 'đ']] as $metric): ?><div class="col-md-4 col-xl-2"><div class="card shadow-sm h-100"><div class="card-body"><div class="text-muted small"><?= esc($metric[0]) ?></div><div class="h5 mb-0"><?= esc((string) $metric[1]) ?></div></div></div></div><?php endforeach; ?></div>
<div class="card shadow-sm"><div class="card-header">Chi tiết theo ngày và chi nhánh</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Ngày</th><th>Chi nhánh</th><th>Booking</th><th>Doanh thu</th><th>Đã thu</th></tr></thead><tbody><?php if (!$report['daily']): ?><tr><td colspan="5" class="text-center text-muted py-4">Không có dữ liệu trong khoảng chọn.</td></tr><?php endif; ?><?php foreach ($report['daily'] as $row): ?><tr><td><?= esc($row['booking_date']) ?></td><td><?= esc($report['branches'][(int) $row['branch_id']] ?? ('#' . $row['branch_id'])) ?></td><td><?= (int) $row['bookings'] ?></td><td><?= number_format((float) $row['revenue'], 0, ',', '.') ?>đ</td><td><?= number_format((float) $row['collected'], 0, ',', '.') ?>đ</td></tr><?php endforeach; ?></tbody></table></div></div>

<?= $this->endSection() ?>
