<?= $this->extend('layouts/admin_master') ?>
<?= $this->section('content') ?>

<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">Danh sách chờ đặt sân</h1><p class="text-muted mb-0">Giữ thứ tự ưu tiên và claim slot bằng transaction.</p></div><form method="post" action="<?= base_url('admin/waitlist/expire') ?>"><?= csrf_field() ?><button class="btn btn-outline-secondary">Dọn mục hết hạn</button></form></div>
<div class="card shadow-sm mb-4"><div class="card-header">Thông báo người chờ tiếp theo</div><div class="card-body"><form method="post" action="<?= base_url('admin/waitlist/notify-next') ?>" class="row g-2 align-items-end"><?= csrf_field() ?><div class="col-md-2"><label class="form-label">Chi nhánh</label><select name="branch_id" class="form-select" required><option value="">-- chọn --</option><?php foreach ($branches as $branch): ?><option value="<?= (int) $branch->id ?>"><?= esc($branch->name) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Sân</label><select name="court_id" class="form-select"><option value="">Bất kỳ</option><?php foreach ($courts as $court): ?><option value="<?= (int) $court->id ?>"><?= esc($court->code) ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Ngày</label><input type="date" name="booking_date" required class="form-control"></div><div class="col-md-2"><label class="form-label">Từ</label><input type="time" name="start_time" required class="form-control"></div><div class="col-md-2"><label class="form-label">Đến</label><input type="time" name="end_time" required class="form-control"></div><div class="col-md-2"><button class="btn btn-outline-primary w-100">Thông báo tiếp theo</button></div></form></div></div>
<div class="row g-4">
    <div class="col-xl-5"><div class="card shadow-sm"><div class="card-header">Thêm vào danh sách chờ</div><div class="card-body"><form method="post" action="<?= base_url('admin/waitlist/store') ?>"><?= csrf_field() ?><div class="row g-2 mb-3"><div class="col-6"><label class="form-label">Chi nhánh</label><select name="branch_id" class="form-select" required><option value="">-- chọn --</option><?php foreach ($branches as $branch): ?><option value="<?= (int) $branch->id ?>"><?= esc($branch->name) ?></option><?php endforeach; ?></select></div><div class="col-6"><label class="form-label">Sân (tùy chọn)</label><select name="court_id" class="form-select"><option value="">Bất kỳ sân</option><?php foreach ($courts as $court): ?><option value="<?= (int) $court->id ?>"><?= esc($court->code) ?></option><?php endforeach; ?></select></div></div><div class="mb-3"><label class="form-label">Người chơi</label><select name="player_id" class="form-select"><option value="">Khách vãng lai</option><?php foreach ($players as $player): ?><option value="<?= (int) $player->id ?>"><?= esc($player->full_name . ' - ' . ($player->phone ?? '')) ?></option><?php endforeach; ?></select></div><div class="row g-2 mb-3"><div class="col-4"><label class="form-label">Ngày</label><input type="date" name="booking_date" required class="form-control"></div><div class="col-4"><label class="form-label">Từ</label><input type="time" name="start_time" required class="form-control"></div><div class="col-4"><label class="form-label">Đến</label><input type="time" name="end_time" required class="form-control"></div></div><div class="row g-2 mb-3"><div class="col-6"><label class="form-label">Tên khách</label><input name="customer_name" class="form-control"></div><div class="col-6"><label class="form-label">Điện thoại</label><input name="customer_phone" class="form-control"></div></div><div class="row g-2 mb-3"><div class="col-6"><label class="form-label">Ưu tiên</label><input name="priority" type="number" min="1" max="10000" value="100" class="form-control"></div><div class="col-6"><label class="form-label">Idempotency key</label><input name="idempotency_key" class="form-control"></div></div><button class="btn btn-primary w-100">Thêm vào waitlist</button></form></div></div></div>
    <div class="col-xl-7"><div class="card shadow-sm"><div class="card-header">Hàng đợi hiện tại</div><div class="table-responsive"><table class="table table-hover align-middle mb-0"><thead><tr><th>Khách</th><th>Slot</th><th>Ưu tiên</th><th>Trạng thái</th><th></th></tr></thead><tbody><?php if (!$entries): ?><tr><td colspan="5" class="text-center text-muted py-4">Chưa có mục chờ.</td></tr><?php endif; ?><?php foreach ($entries as $entry): ?><tr><td><?= esc($entry->customer_name) ?><br><small class="text-muted"><?= esc($entry->customer_phone) ?></small></td><td><?= esc($entry->booking_date . ' ' . substr($entry->start_time, 0, 5) . '-' . substr($entry->end_time, 0, 5)) ?></td><td><?= (int) $entry->priority ?></td><td><span class="badge text-bg-<?= in_array($entry->status, ['waiting', 'notified'], true) ? 'warning' : ($entry->status === 'claimed' ? 'success' : 'secondary') ?>"><?= esc($entry->status) ?></span></td><td class="text-nowrap"><?php if (in_array($entry->status, ['waiting', 'notified'], true)): ?><form method="post" action="<?= base_url('admin/waitlist/claim/' . $entry->id) ?>" class="d-inline"><?= csrf_field() ?><button class="btn btn-sm btn-outline-success">Claim</button></form><form method="post" action="<?= base_url('admin/waitlist/cancel/' . $entry->id) ?>" class="d-inline"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger">Hủy</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div></div>
</div>

<?= $this->endSection() ?>
