<?= $this->extend('layouts/admin_master') ?>
<?= $this->section('content') ?>
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h4 mb-1">Coach & Clinic</h1><p class="text-muted mb-0">HLV, availability, lớp học và điểm danh.</p></div><form class="d-flex gap-2" method="get"><input type="date" name="date" value="<?= esc($date) ?>" class="form-control"><button class="btn btn-outline-secondary">Xem ngày</button></form></div>
<div class="row g-4">
    <div class="col-xl-4">
        <div class="card shadow-sm mb-4"><div class="card-header">Tạo coach</div><div class="card-body"><form method="post" action="<?= base_url('admin/coaching/coaches/store') ?>"><?= csrf_field() ?><select name="branch_id" class="form-select mb-2" required><option value="">-- chi nhánh --</option><?php foreach ($branches as $branch): ?><option value="<?= (int)$branch->id ?>"><?= esc($branch->name) ?></option><?php endforeach; ?></select><input name="full_name" class="form-control mb-2" placeholder="Họ tên" required><input name="phone" class="form-control mb-2" placeholder="Điện thoại"><input type="number" step="0.01" min="0" name="hourly_rate" class="form-control" placeholder="Giá/giờ"><button class="btn btn-primary w-100 mt-3">Lưu coach</button></form></div></div>
        <div class="card shadow-sm mb-4"><div class="card-header">Availability</div><div class="card-body"><form method="post" action="<?= base_url('admin/coaching/availability/store') ?>"><?= csrf_field() ?><select name="coach_id" class="form-select mb-2" required><option value="">-- coach --</option><?php foreach ($coaches as $coach): ?><option value="<?= (int)$coach->id ?>"><?= esc($coach->full_name) ?></option><?php endforeach; ?></select><select name="branch_id" class="form-select mb-2"><option value="">Tất cả chi nhánh</option><?php foreach ($branches as $branch): ?><option value="<?= (int)$branch->id ?>"><?= esc($branch->name) ?></option><?php endforeach; ?></select><div class="row g-2"><div class="col-4"><select name="day_of_week" class="form-select"><?php foreach(['CN','T2','T3','T4','T5','T6','T7'] as $day=>$label): ?><option value="<?=$day?>"><?=$label?></option><?php endforeach; ?></select></div><div class="col-4"><input type="time" name="start_time" class="form-control" required></div><div class="col-4"><input type="time" name="end_time" class="form-control" required></div></div><button class="btn btn-outline-primary w-100 mt-3">Thêm lịch</button></form></div></div>
        <div class="card shadow-sm"><div class="card-header">Blackout</div><div class="card-body"><form method="post" action="<?= base_url('admin/coaching/blackouts/store') ?>"><?= csrf_field() ?><select name="coach_id" class="form-select mb-2" required><option value="">-- coach --</option><?php foreach ($coaches as $coach): ?><option value="<?= (int)$coach->id ?>"><?= esc($coach->full_name) ?></option><?php endforeach; ?></select><div class="row g-2"><div class="col-6"><input type="datetime-local" name="start_at" class="form-control" required></div><div class="col-6"><input type="datetime-local" name="end_at" class="form-control" required></div></div><input name="reason" class="form-control mt-2" placeholder="Lý do"><button class="btn btn-outline-danger w-100 mt-3">Tạo blackout</button></form></div></div>
    </div>
    <div class="col-xl-8">
        <div class="card shadow-sm mb-4"><div class="card-header">Tạo lesson / clinic</div><div class="card-body"><form method="post" action="<?= base_url('admin/coaching/sessions/store') ?>"><?= csrf_field() ?><div class="row g-2 mb-2"><div class="col-md-5"><input name="title" class="form-control" placeholder="Tên session" required></div><div class="col-md-3"><select name="session_type" class="form-select"><option value="private">Private</option><option value="semi_private">Semi-private</option><option value="group">Group</option><option value="clinic">Clinic</option></select></div><div class="col-md-4"><select name="coach_id" class="form-select" required><option value="">-- coach --</option><?php foreach($coaches as $coach): ?><option value="<?= (int)$coach->id ?>"><?= esc($coach->full_name) ?></option><?php endforeach; ?></select></div></div><div class="row g-2 mb-2"><div class="col-md-4"><select name="branch_id" class="form-select" required><option value="">-- chi nhánh --</option><?php foreach($branches as $branch): ?><option value="<?= (int)$branch->id ?>"><?= esc($branch->name) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><select name="court_id" class="form-select"><option value="">Không giữ sân</option><?php foreach($courts as $court): ?><option value="<?= (int)$court->id ?>"><?= esc($court->display_name ?? ($court->name_vi ?? $court->code)) ?></option><?php endforeach; ?></select></div><div class="col-md-4"><input type="date" name="session_date" value="<?= esc($date) ?>" class="form-control" required></div></div><div class="row g-2"><div class="col-4"><input type="time" name="start_time" class="form-control" required></div><div class="col-4"><input type="time" name="end_time" class="form-control" required></div><div class="col-2"><input type="number" name="capacity" min="1" max="50" value="1" class="form-control" required></div><div class="col-2"><input type="number" step="0.01" min="0" name="price_per_player" value="0" class="form-control"></div></div><button class="btn btn-primary mt-3">Tạo session</button></form></div></div>
        <div class="card shadow-sm"><div class="card-header">Session ngày <?= esc($date) ?></div><div class="table-responsive"><table class="table table-sm align-middle mb-0"><thead><tr><th>Session</th><th>Coach</th><th>Giờ</th><th>Học viên / điểm danh</th><th>Trạng thái</th><th></th></tr></thead><tbody><?php if(!$sessions): ?><tr><td colspan="6" class="text-muted text-center py-4">Chưa có session.</td></tr><?php endif; ?><?php foreach($sessions as $session): ?><tr><td><strong><?= esc($session->title) ?></strong><div class="small text-muted"><?= esc($session->session_type) ?> · <?= esc($session->branch_name ?? '-') ?></div></td><td><?= esc($session->coach_name ?? '-') ?></td><td><?= esc(substr($session->start_time,0,5).'–'.substr($session->end_time,0,5)) ?></td><td><?php foreach(($players[(int)$session->id]??[]) as $entry): ?><div class="mb-1"><span><?= esc($entry->full_name ?? ('#'.$entry->player_id)) ?> · <?= esc($entry->status) ?></span><?php if(in_array($entry->status,['requested','waitlisted'],true)): ?><form method="post" action="<?= base_url('admin/coaching/approve/'.$entry->id) ?>" class="d-inline"><?= csrf_field() ?><button class="btn btn-link btn-sm p-0">Duyệt</button></form><?php elseif($entry->status==='approved'): ?><form method="post" action="<?= base_url('admin/coaching/attendance/'.$entry->id) ?>" class="d-inline-flex gap-1 ms-1"><?= csrf_field() ?><select name="status" class="form-select form-select-sm py-0" style="width:92px"><option value="attended">Có mặt</option><option value="no_show">No-show</option><option value="registered">Chưa đến</option></select><button class="btn btn-link btn-sm p-0">Lưu</button></form><?php endif; ?></div><?php endforeach; ?></td><td><span class="badge text-bg-<?= in_array($session->status,['open','full'],true)?'success':'secondary' ?>"><?= esc($session->status) ?></span></td><td><?php if(!in_array($session->status,['cancelled','completed'],true)): ?><form method="post" action="<?= base_url('admin/coaching/cancel/'.$session->id) ?>"><?= csrf_field() ?><button class="btn btn-sm btn-outline-danger">Hủy</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div>
    </div>
</div>
<?= $this->endSection() ?>
