<?= view('sales/partials/header', ['pageTitle' => $pageTitle, 'active' => 'solutions', 'salesLocale' => $salesLocale]) ?>
<section class="sales-hero sales-container">
    <div class="sales-hero-copy"><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_eyebrow')) ?></span><h1><?= nl2br(esc(lang('Sales.solutions_title'))) ?></h1><p><?= esc(lang('Sales.solutions_lede')) ?></p><div class="sales-hero-actions"><a class="sales-button" href="<?= esc(site_url('demo')) ?>"><?= esc(lang('Sales.start_trial')) ?> <span>↗</span></a><a class="sales-text-link" href="<?= esc(site_url('pricing')) ?>"><?= esc(lang('Sales.view_pricing')) ?> <span>↗</span></a></div><small class="sales-proof">◎ <?= esc(lang('Sales.solutions_proof')) ?></small></div>
    <div class="sales-hero-art"><div class="orbit orbit-a"></div><div class="orbit orbit-b"></div><div class="hero-panel"><span>NETWORK / 01</span><strong>OPERATE<br><em>BETTER.</em></strong><div><i></i><i></i><i></i></div><small>COURTS · CLUBS · EVENTS · DATA</small></div></div>
</section>
<section class="sales-section sales-container"><div class="sales-section-heading"><div><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_section_eyebrow')) ?></span><h2><?= nl2br(esc(lang('Sales.solutions_section_title'))) ?></h2></div><p><?= esc(lang('Sales.solutions_section_lede')) ?></p></div>
    <div class="product-grid">
        <?php foreach ([['court','court-management','01'],['club','club','02'],['tournament','tournament','03'],['ranking','ranking-pro','04'],['api','api','05'],['association','association','06']] as [$key, $slug, $number]): ?>
            <?php $prefix = $key === 'association' ? 'association' : 'product_' . $key; ?>
            <a class="product-card" href="<?= esc(site_url('solutions/' . $slug)) ?>"><span class="product-card-number"><?= $number ?></span><span class="sales-eyebrow"><?= esc(lang('Sales.' . $prefix . '_label')) ?></span><h3><?= esc(lang('Sales.' . $prefix . '_name')) ?></h3><p><?= esc(lang('Sales.' . $prefix . '_short')) ?></p><span class="product-card-link"><?= esc(lang('Sales.learn_more')) ?> <b>↗</b></span></a>
        <?php endforeach; ?>
    </div>
</section>
<section class="problem-section"><div class="sales-container"><div class="sales-section-heading"><div><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_problem_eyebrow')) ?></span><h2><?= nl2br(esc(lang('Sales.solutions_problem_title'))) ?></h2></div><p><?= esc(lang('Sales.solutions_problem_lede')) ?></p></div><div class="pain-grid"><?php for ($i = 1; $i <= 3; $i++): ?><article class="pain-card"><span>0<?= $i ?></span><h3><?= esc(lang('Sales.solutions_pain_' . $i . '_title')) ?></h3><p><?= esc(lang('Sales.solutions_pain_' . $i . '_desc')) ?></p></article><?php endfor; ?></div></div></section>
<section class="answer-section sales-container"><div class="answer-copy"><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_answer_eyebrow')) ?></span><h2><?= nl2br(esc(lang('Sales.solutions_answer_title'))) ?></h2><p><?= esc(lang('Sales.solutions_answer_lede')) ?></p><a class="sales-text-link" href="<?= esc(site_url('demo')) ?>"><?= esc(lang('Sales.book_demo')) ?> <span>↗</span></a></div><div class="answer-flow"><div><b>01</b><span><?= esc(lang('Sales.workflow_1')) ?></span><small><?= esc(lang('Sales.workflow_1_desc')) ?></small></div><i>→</i><div><b>02</b><span><?= esc(lang('Sales.workflow_2')) ?></span><small><?= esc(lang('Sales.workflow_2_desc')) ?></small></div><i>→</i><div><b>03</b><span><?= esc(lang('Sales.workflow_3')) ?></span><small><?= esc(lang('Sales.workflow_3_desc')) ?></small></div></div></section>
<section class="audience-section"><div class="sales-container"><div class="sales-section-heading sales-section-heading-light"><div><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_audience_eyebrow')) ?></span><h2><?= esc(lang('Sales.solutions_audience_title')) ?></h2></div></div><div class="audience-grid"><?php foreach (['court','club','tournament','player','developer','association'] as $audience): ?><a href="<?= esc(site_url($audience === 'player' ? 'ranking/pro' : ($audience === 'developer' ? 'developers' : 'solutions/' . ($audience === 'court' ? 'court-management' : $audience)))) ?>"><span><?= strtoupper($audience) ?></span><p><?= esc(lang('Sales.solutions_audience_' . $audience)) ?></p><b>↗</b></a><?php endforeach; ?></div></div></section>
<section class="sales-loop"><div class="sales-container"><div class="sales-section-heading sales-section-heading-light"><div><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_workflow_eyebrow')) ?></span><h2><?= nl2br(esc(lang('Sales.solutions_workflow_title'))) ?></h2></div><p><?= esc(lang('Sales.solutions_workflow_lede')) ?></p></div><div class="loop-grid"><?php for ($i = 1; $i <= 4; $i++): ?><div class="loop-item"><span>0<?= $i ?></span><strong><?= esc(lang('Sales.workflow_' . $i)) ?></strong><p><?= esc(lang('Sales.workflow_' . $i . '_desc')) ?></p></div><?php endfor; ?></div></div></section>
<section class="sales-cta sales-container"><div><span class="sales-eyebrow"><?= esc(lang('Sales.solutions_eyebrow')) ?></span><h2><?= nl2br(esc(lang('Sales.solutions_final_title'))) ?></h2><p><?= esc(lang('Sales.solutions_final_lede')) ?></p></div><div><a class="sales-button" href="<?= esc(site_url('demo')) ?>"><?= esc(lang('Sales.book_demo')) ?> <span>↗</span></a><a class="sales-text-link" href="<?= esc(site_url('pricing')) ?>"><?= esc(lang('Sales.view_pricing')) ?> <span>↗</span></a></div></section>
<?= view('sales/partials/footer') ?>
