<?php
$prefix = $product === 'association' ? 'association' : 'product_' . $product;
$slug = ['court' => 'court-management', 'club' => 'club', 'tournament' => 'tournament', 'ranking' => 'ranking-pro', 'api' => 'api', 'association' => 'association'][$product];
$featureCount = $product === 'court' ? 12 : ($product === 'association' || $product === 'api' || $product === 'ranking' ? 8 : 8);
?>
<?= view('sales/partials/header', ['pageTitle' => $pageTitle, 'active' => $product === 'api' ? 'api' : 'solutions', 'salesLocale' => $salesLocale]) ?>
<section class="product-hero sales-container"><div><a class="back-link" href="<?= esc(site_url('solutions')) ?>">← <?= esc(lang('Sales.all_products')) ?></a><span class="sales-eyebrow"><?= esc(lang('Sales.' . $prefix . '_label')) ?></span><h1><?= nl2br(esc(lang('Sales.' . $prefix . '_title'))) ?></h1><p><?= esc(lang('Sales.' . $prefix . '_lede')) ?></p><div class="sales-hero-actions"><div><a class="sales-button" href="<?= esc(site_url('demo')) ?>"><?= esc($product === 'association' ? lang('Sales.contact_sales') : lang('Sales.start_trial')) ?> <span>↗</span></a><small class="cta-note"><?= esc(lang('Sales.product_cta_note')) ?></small></div><a class="sales-text-link" href="<?= esc(site_url('pricing')) ?>"><?= esc(lang('Sales.view_pricing')) ?> <span>↗</span></a></div></div><aside class="product-hero-note"><span>◎</span><strong><?= esc(lang('Sales.' . $prefix . '_message')) ?></strong><small><b><?= esc(lang('Sales.product_for')) ?>:</b> <?= esc(lang('Sales.' . $prefix . '_audience')) ?></small></aside></section>
<section class="value-strip sales-container"><div><span class="sales-eyebrow"><?= esc(lang('Sales.product_value_label')) ?></span><h2><?= esc(lang('Sales.product_value_title')) ?></h2></div><div class="value-points"><?php for ($i = 1; $i <= 3; $i++): ?><div><b>0<?= $i ?></b><span><?= esc(lang('Sales.' . $prefix . '_benefit_' . $i)) ?></span></div><?php endfor; ?></div></section>
<section class="feature-section sales-container"><div class="feature-heading"><span class="sales-eyebrow">01 / <?= esc(lang('Sales.product_features')) ?></span><h2><?= esc(lang('Sales.' . $prefix . '_name')) ?><br><em><?= esc(lang('Sales.product_features')) ?></em></h2></div><div class="feature-grid"><?php for ($i = 1; $i <= $featureCount; $i++): ?><div class="feature-item"><span><?= str_pad((string) $i, 2, '0', STR_PAD_LEFT) ?></span><strong><?= esc(lang('Sales.' . $prefix . '_feature_' . $i)) ?></strong><b>↗</b></div><?php endfor; ?></div></section>
<section class="product-steps"><div class="sales-container"><div class="sales-section-heading"><div><span class="sales-eyebrow">02 / <?= esc(lang('Sales.product_steps')) ?></span><h2><?= esc(lang('Sales.solutions_workflow_title')) ?></h2></div></div><div class="steps-grid"><?php for ($i = 1; $i <= 3; $i++): ?><div class="step-card"><span>0<?= $i ?></span><strong><?= esc(lang('Sales.' . $prefix . '_step_' . $i)) ?></strong></div><?php endfor; ?></div></div></section>
<section class="faq-section sales-container"><span class="sales-eyebrow">03 / FAQ</span><h2><?= esc(lang('Sales.product_faq')) ?></h2><div class="faq-grid"><?php for ($i = 1; $i <= 3; $i++): ?><details><summary><?= esc(lang('Sales.product_faq_' . $i . '_q')) ?><span>+</span></summary><p><?= esc(lang('Sales.product_faq_' . $i . '_a')) ?></p></details><?php endfor; ?></div></section>
<section class="sales-cta sales-container"><div><span class="sales-eyebrow"><?= esc(lang('Sales.' . $prefix . '_label')) ?></span><h2><?= esc(lang('Sales.solutions_final_title')) ?></h2></div><a class="sales-button" href="<?= esc(site_url('demo')) ?>"><?= esc(lang('Sales.book_demo')) ?> <span>↗</span></a></section>
<?= view('sales/partials/footer') ?>
