<?php
$locale = service('language')->getLocale();
$label = ['singles' => 'Đơn', 'doubles' => 'Đôi', 'mixed_doubles' => 'Đôi nam nữ'];
$date = static fn ($value) => $value ? date('d/m/Y', strtotime((string) $value)) : '—';
?>
<!doctype html><html lang="<?= esc($locale) ?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= esc($pageTitle) ?></title><meta name="description" content="<?= esc($metaDescription) ?>"><link rel="stylesheet" href="<?= esc(asset_url('assets/css/public-portal.css')) ?>"><link rel="stylesheet" href="<?= esc(asset_url('assets/css/athlete-public.css')) ?>"></head>
<body class="athlete-body">
<header class="athlete-header"><div class="athlete-container nav-inner"><a class="athlete-brand" href="/"><span class="brand-badge">NP</span><span><b>NATIONAL</b><small>PICKLEBALL RANKING</small></span></a><nav><a class="active" href="/ranking">BXH</a><a href="/players">VĐV</a><a href="/tournaments">Giải đấu</a><a href="/live">Live</a></nav><div class="nav-right"><a href="/locale/switch/<?= $locale === 'vi' ? 'en' : 'vi' ?>"><?= $locale === 'vi' ? 'EN' : 'VI' ?></a><a class="nav-cta" href="/login">Khu vực của tôi ↗</a></div></div></header>
<main><section class="rank-hero"><div class="athlete-container rank-hero-grid"><div><span class="eyebrow light">NATIONAL LEADERBOARD · 2026</span><h1>Những người<br><em>đang dẫn đầu.</em></h1><p>Leaderboard chính thức dựa trên canonical Rating, Reliability và các kết quả đã được xác minh.</p><div class="hero-pills"><span><i></i> VERIFIED DATA</span><span>LAST UPDATED <?= esc($date($lastUpdated)) ?></span></div></div><div class="rank-hero-card"><span>TOP ATHLETE</span><strong><?= esc($rankings[0]['name'] ?? 'Đang cập nhật') ?></strong><small><?= esc($rankings[0]['province'] ?? 'Toàn quốc') ?> · <?= esc($rankings[0]['skill_band'] ?? 'NR') ?></small><b><?= isset($rankings[0]['rating']) ? number_format((float) $rankings[0]['rating'], 3) : '—' ?><i> RATING</i></b><a href="<?= !empty($rankings[0]['player_code']) ? '/players/' . esc($rankings[0]['player_code']) : '/players' ?>">Mở hồ sơ VĐV ↗</a></div></div></section>
<section class="athlete-container rank-content"><div class="rank-toolbar"><div><span class="eyebrow">01 / CANONICAL RANKING</span><h2>Bảng xếp hạng quốc gia</h2></div><div class="rank-tabs"><?php foreach ($label as $key => $text): ?><a class="<?= $discipline === $key ? 'active' : '' ?>" href="/ranking?discipline=<?= esc($key) ?>"><?= esc($text) ?></a><?php endforeach; ?></div></div><div class="rank-table-card"><div class="rank-table-head"><span>HẠNG</span><span>VẬN ĐỘNG VIÊN</span><span>TỈNH / CLB</span><span>RATING</span><span>RELIABILITY</span><span>TRẬN</span></div><?php if (empty($rankings)): ?><div class="empty-state">Chưa có dữ liệu xếp hạng cho nội dung này.</div><?php endif; ?><?php foreach ($rankings as $row): ?><a class="rank-row" href="/players/<?= esc($row['player_code'] ?: $row['player_id']) ?>"><span class="rank-pos">#<?= (int) $row['rank'] ?></span><span class="rank-player"><i><?= esc(mb_strtoupper(mb_substr($row['name'] ?: '?', 0, 1))) ?></i><b><?= esc($row['name']) ?><small><?= esc($row['national_player_id'] ?: $row['player_code'] ?: 'National Player') ?></small></b></span><span class="rank-place"><?= esc($row['province'] ?: '—') ?><small><?= esc($row['club'] ?: 'CLB độc lập') ?></small></span><strong class="rank-rating"><?= number_format((float) $row['rating'], 3) ?><small><?= esc($row['skill_band'] ?: 'NR') ?></small></strong><span class="rank-reliability"><?= number_format((float) ($row['reliability'] ?? 0), 0) ?>%</span><span class="rank-matches"><?= number_format((int) ($row['match_count'] ?? 0)) ?><small>official</small></span><span class="rank-arrow">↗</span></a><?php endforeach; ?></div><div class="rank-note"><span><i></i> Canonical player profile · Privacy-safe public data</span><a href="/#methodology">Xem methodology ↗</a></div></section></main>
<footer class="athlete-footer"><div class="athlete-container"><a class="athlete-brand" href="/"><span class="brand-badge">NP</span><span><b>NATIONAL</b><small>PICKLEBALL RANKING</small></span></a><p>Hồ sơ thi đấu có nguồn, lịch sử và khả năng kiểm chứng.</p></div></footer>
</body></html>
